package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/rohit21755/groveserverv2/graph/generated"
	"github.com/rohit21755/groveserverv2/graph/model"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.TaskInput) (*model.Task, error) {
	panic(fmt.Errorf("not implemented: CreateTask - createTask"))
}

// ApproveSubmission is the resolver for the approveSubmission field.
func (r *mutationResolver) ApproveSubmission(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: ApproveSubmission - approveSubmission"))
}

// RejectSubmission is the resolver for the rejectSubmission field.
func (r *mutationResolver) RejectSubmission(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: RejectSubmission - rejectSubmission"))
}

// CreateEngagementEvent is the resolver for the createEngagementEvent field.
func (r *mutationResolver) CreateEngagementEvent(ctx context.Context, input model.EngagementEventInput) (*model.EngagementEvent, error) {
	panic(fmt.Errorf("not implemented: CreateEngagementEvent - createEngagementEvent"))
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, input model.MessageInput) (*model.Message, error) {
	panic(fmt.Errorf("not implemented: SendMessage - sendMessage"))
}

// RedeemReward is the resolver for the redeemReward field.
func (r *mutationResolver) RedeemReward(ctx context.Context, rewardID string) (*model.Reward, error) {
	panic(fmt.Errorf("not implemented: RedeemReward - redeemReward"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, state *string, college *string) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// Leaderboard is the resolver for the leaderboard field.
func (r *queryResolver) Leaderboard(ctx context.Context, scope string, period *string, scopeValue *string) ([]*model.LeaderboardEntry, error) {
	panic(fmt.Errorf("not implemented: Leaderboard - leaderboard"))
}

// EngagementEvents is the resolver for the engagementEvents field.
func (r *queryResolver) EngagementEvents(ctx context.Context) ([]*model.EngagementEvent, error) {
	panic(fmt.Errorf("not implemented: EngagementEvents - engagementEvents"))
}

// CompletedTaskFeed is the resolver for the completedTaskFeed field.
func (r *queryResolver) CompletedTaskFeed(ctx context.Context) ([]*model.CompletedTaskFeedItem, error) {
	panic(fmt.Errorf("not implemented: CompletedTaskFeed - completedTaskFeed"))
}

// UserCompletedTasks is the resolver for the userCompletedTasks field.
func (r *queryResolver) UserCompletedTasks(ctx context.Context, userID string) ([]*model.CompletedTaskFeedItem, error) {
	panic(fmt.Errorf("not implemented: UserCompletedTasks - userCompletedTasks"))
}

// ChatRooms is the resolver for the chatRooms field.
func (r *queryResolver) ChatRooms(ctx context.Context) ([]*model.ChatRoom, error) {
	panic(fmt.Errorf("not implemented: ChatRooms - chatRooms"))
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context, roomID string) ([]*model.Message, error) {
	panic(fmt.Errorf("not implemented: Messages - messages"))
}

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context) ([]*model.Notification, error) {
	panic(fmt.Errorf("not implemented: Notifications - notifications"))
}

// MessageAdded is the resolver for the messageAdded field.
func (r *subscriptionResolver) MessageAdded(ctx context.Context, roomID string) (<-chan *model.Message, error) {
	panic(fmt.Errorf("not implemented: MessageAdded - messageAdded"))
}

// LeaderboardUpdated is the resolver for the leaderboardUpdated field.
func (r *subscriptionResolver) LeaderboardUpdated(ctx context.Context, scope string) (<-chan *model.LeaderboardEntry, error) {
	panic(fmt.Errorf("not implemented: LeaderboardUpdated - leaderboardUpdated"))
}

// NotificationReceived is the resolver for the notificationReceived field.
func (r *subscriptionResolver) NotificationReceived(ctx context.Context) (<-chan *model.Notification, error) {
	panic(fmt.Errorf("not implemented: NotificationReceived - notificationReceived"))
}

// TaskCompletedFeed is the resolver for the taskCompletedFeed field.
func (r *subscriptionResolver) TaskCompletedFeed(ctx context.Context) (<-chan *model.CompletedTaskFeedItem, error) {
	panic(fmt.Errorf("not implemented: TaskCompletedFeed - taskCompletedFeed"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}
func (r *mutationResolver) Register(ctx context.Context, email string, password string, name string) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Register - register"))
}
func (r *mutationResolver) FollowUser(ctx context.Context, userID string) (bool, error) {
	panic(fmt.Errorf("not implemented: FollowUser - followUser"))
}
func (r *mutationResolver) UnfollowUser(ctx context.Context, userID string) (bool, error) {
	panic(fmt.Errorf("not implemented: UnfollowUser - unfollowUser"))
}
func (r *mutationResolver) UploadResume(ctx context.Context, file string) (bool, error) {
	panic(fmt.Errorf("not implemented: UploadResume - uploadResume"))
}
func (r *mutationResolver) SubmitTask(ctx context.Context, taskID string, submission string) (*model.TaskSubmission, error) {
	panic(fmt.Errorf("not implemented: SubmitTask - submitTask"))
}
func (r *mutationResolver) ReactToFeed(ctx context.Context, feedID string, reaction string) (bool, error) {
	panic(fmt.Errorf("not implemented: ReactToFeed - reactToFeed"))
}
func (r *mutationResolver) CommentOnFeed(ctx context.Context, feedID string, comment string) (*model.Comment, error) {
	panic(fmt.Errorf("not implemented: CommentOnFeed - commentOnFeed"))
}
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input model.TaskInput) (*model.Task, error) {
	panic(fmt.Errorf("not implemented: UpdateTask - updateTask"))
}
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "OK", nil
}
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	panic(fmt.Errorf("not implemented: Tasks - tasks"))
}
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	panic(fmt.Errorf("not implemented: Task - task"))
}
func (r *queryResolver) Feed(ctx context.Context) ([]*model.FeedItem, error) {
	panic(fmt.Errorf("not implemented: Feed - feed"))
}
func (r *queryResolver) UserFeed(ctx context.Context, userID string) ([]*model.FeedItem, error) {
	panic(fmt.Errorf("not implemented: UserFeed - userFeed"))
}
func (r *queryResolver) PanIndiaLeaderboard(ctx context.Context) ([]*model.LeaderboardEntry, error) {
	panic(fmt.Errorf("not implemented: PanIndiaLeaderboard - panIndiaLeaderboard"))
}
func (r *queryResolver) StateLeaderboard(ctx context.Context) ([]*model.LeaderboardEntry, error) {
	panic(fmt.Errorf("not implemented: StateLeaderboard - stateLeaderboard"))
}
func (r *queryResolver) CollegeLeaderboard(ctx context.Context) ([]*model.LeaderboardEntry, error) {
	panic(fmt.Errorf("not implemented: CollegeLeaderboard - collegeLeaderboard"))
}
func (r *queryResolver) ChatRoom(ctx context.Context, id string) (*model.ChatRoom, error) {
	panic(fmt.Errorf("not implemented: ChatRoom - chatRoom"))
}
func (r *subscriptionResolver) FeedUpdates(ctx context.Context) (<-chan *model.FeedItem, error) {
	panic(fmt.Errorf("not implemented: FeedUpdates - feedUpdates"))
}
func (r *subscriptionResolver) ChatMessages(ctx context.Context, roomID string) (<-chan *model.ChatMessage, error) {
	panic(fmt.Errorf("not implemented: ChatMessages - chatMessages"))
}
func (r *subscriptionResolver) Notifications(ctx context.Context) (<-chan *model.Notification, error) {
	panic(fmt.Errorf("not implemented: Notifications - notifications"))
}
*/
