// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChatRoom struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Type      string  `json:"type"`
	CreatedBy string  `json:"createdBy"`
	CreatedAt string  `json:"createdAt"`
	Members   []*User `json:"members"`
}

type CompletedTaskFeedItem struct {
	ID           string          `json:"id"`
	SubmissionID string          `json:"submissionId"`
	UserID       string          `json:"userId"`
	TaskID       string          `json:"taskId"`
	Visibility   string          `json:"visibility"`
	CreatedAt    string          `json:"createdAt"`
	User         *User           `json:"user"`
	Task         *Task           `json:"task"`
	Submission   *Submission     `json:"submission"`
	Reactions    []*FeedReaction `json:"reactions"`
	Comments     []*FeedComment  `json:"comments"`
}

type EngagementEvent struct {
	ID           string              `json:"id"`
	Type         string              `json:"type"`
	Title        string              `json:"title"`
	Description  string              `json:"description"`
	StartAt      string              `json:"startAt"`
	EndAt        string              `json:"endAt"`
	Rules        string              `json:"rules"`
	Reward       string              `json:"reward"`
	Participants []*EventParticipant `json:"participants"`
	Submissions  []*EventSubmission  `json:"submissions"`
}

type EngagementEventInput struct {
	Type        string `json:"type"`
	Title       string `json:"title"`
	Description string `json:"description"`
	StartAt     string `json:"startAt"`
	EndAt       string `json:"endAt"`
	Rules       string `json:"rules"`
	Reward      string `json:"reward"`
}

type EventParticipant struct {
	EventID string `json:"eventId"`
	UserID  string `json:"userId"`
	Score   int    `json:"score"`
	User    *User  `json:"user"`
}

type EventSubmission struct {
	ID      string       `json:"id"`
	EventID string       `json:"eventId"`
	UserID  string       `json:"userId"`
	Content string       `json:"content"`
	Votes   []*EventVote `json:"votes"`
	User    *User        `json:"user"`
}

type EventVote struct {
	EventID      string `json:"eventId"`
	SubmissionID string `json:"submissionId"`
	VoterID      string `json:"voterId"`
	CreatedAt    string `json:"createdAt"`
}

type FeedComment struct {
	ID        string `json:"id"`
	FeedID    string `json:"feedId"`
	UserID    string `json:"userId"`
	Comment   string `json:"comment"`
	CreatedAt string `json:"createdAt"`
	User      *User  `json:"user"`
}

type FeedReaction struct {
	FeedID    string `json:"feedId"`
	UserID    string `json:"userId"`
	Reaction  string `json:"reaction"`
	CreatedAt string `json:"createdAt"`
}

type LeaderboardEntry struct {
	LeaderboardID string `json:"leaderboardId"`
	UserID        string `json:"userId"`
	Rank          int    `json:"rank"`
	Xp            int    `json:"xp"`
	User          *User  `json:"user"`
}

type Message struct {
	ID        string             `json:"id"`
	RoomID    string             `json:"roomId"`
	SenderID  string             `json:"senderId"`
	Type      string             `json:"type"`
	Content   string             `json:"content"`
	CreatedAt string             `json:"createdAt"`
	Sender    *User              `json:"sender"`
	Reactions []*MessageReaction `json:"reactions"`
}

type MessageInput struct {
	RoomID  string `json:"roomId"`
	Type    string `json:"type"`
	Content string `json:"content"`
}

type MessageReaction struct {
	MessageID string `json:"messageId"`
	UserID    string `json:"userId"`
	Reaction  string `json:"reaction"`
	CreatedAt string `json:"createdAt"`
}

type Mutation struct {
}

type Notification struct {
	ID        string `json:"id"`
	UserID    string `json:"userId"`
	Title     string `json:"title"`
	Body      string `json:"body"`
	Type      string `json:"type"`
	IsRead    bool   `json:"isRead"`
	CreatedAt string `json:"createdAt"`
}

type Query struct {
}

type Reward struct {
	ID         string `json:"id"`
	Type       string `json:"type"`
	Value      string `json:"value"`
	RedeemedAt string `json:"redeemedAt"`
}

type Submission struct {
	ID           string  `json:"id"`
	TaskID       string  `json:"taskId"`
	UserID       string  `json:"userId"`
	ProofURL     string  `json:"proofUrl"`
	Status       string  `json:"status"`
	AdminComment *string `json:"adminComment,omitempty"`
	ReviewedBy   *string `json:"reviewedBy,omitempty"`
	CreatedAt    string  `json:"createdAt"`
}

type Subscription struct {
}

type Task struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Xp          int     `json:"xp"`
	Type        string  `json:"type"`
	ProofType   string  `json:"proofType"`
	Priority    string  `json:"priority"`
	StartAt     *string `json:"startAt,omitempty"`
	EndAt       *string `json:"endAt,omitempty"`
	IsFlash     bool    `json:"isFlash"`
	IsWeekly    bool    `json:"isWeekly"`
	CreatedBy   string  `json:"createdBy"`
	CreatedAt   string  `json:"createdAt"`
}

type TaskInput struct {
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Xp          int     `json:"xp"`
	Type        string  `json:"type"`
	ProofType   string  `json:"proofType"`
	Priority    string  `json:"priority"`
	StartAt     *string `json:"startAt,omitempty"`
	EndAt       *string `json:"endAt,omitempty"`
	IsFlash     bool    `json:"isFlash"`
	IsWeekly    bool    `json:"isWeekly"`
}

type User struct {
	ID               string  `json:"id"`
	Name             string  `json:"name"`
	Email            string  `json:"email"`
	Phone            *string `json:"phone,omitempty"`
	College          *string `json:"college,omitempty"`
	State            *string `json:"state,omitempty"`
	Role             string  `json:"role"`
	Xp               int     `json:"xp"`
	Level            int     `json:"level"`
	Coins            int     `json:"coins"`
	Bio              *string `json:"bio,omitempty"`
	AvatarURL        *string `json:"avatarUrl,omitempty"`
	ResumeURL        *string `json:"resumeUrl,omitempty"`
	ResumeVisibility string  `json:"resumeVisibility"`
	ReferralCode     string  `json:"referralCode"`
	CreatedAt        string  `json:"createdAt"`
}
